### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [yletfull/spr10#3]
Здравствуйте. 
Благодарю за проделанную работу!
К сожалению текущая реализация содержит ряд недостатков, не позволяющих мне засчитать работу на данной итерации:

Репозиторий:
**Нужно исправить:** отсутствуют git-теги отражающие номер версии. Создать их можно при помощи команды `git tag -a v0.0.1 -m "my first version"`
Обращаю внимание что теги по-умолчанию не публикуются при вызове команды `git push`
Для их публикации выполните команду `git push origin --tags`
Подробнее: https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BC%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8

**Можно лучше** Присутствует лишний файл `sh-keygen -t rsa -b 4096 -C ylet-logi@mail.ru`

**Можно лучше** файлы logo.svg и cover.jpg, расположенные в репозитории не используются на страничке (загружаются с серверов Яндекса). Просьба либо задействовать их либо удалить

**Нужно исправить**: README файл должен содержать номер версии (ненулевой), ссылку на проект (github pages) и заголовок отражающий назначение проекта.
В дополнение к ссылкам из практики рекомендую почитать статью "Как написать хороший README?". Ссылка на статью:

https://medium.com/astrolabe/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B8%D0%B9-readme-159f88076b26

Примеры шаблонов для README:

- https://gist.github.com/PurpleBooth/109311bb0361f32d87a2,

- https://gist.github.com/fvcproductions/1bfc2d4aecb01a834b46

Регулярные выражения:
**Можно лучше** Квантификатор {1,} можно заменить на +. Так будет лаконичнее.
**Можно лучше** Квантификатор {1} можно не использовать. Он не играет никакой роли.

Имя:
**Нужно исправить**: не проходят валидацию имена содержащие букву Ё.
Пример: Ерёма

Email:
**Нужно исправить** Валидацию не проходят следующие корректные адреса:
some@ya-2.ru - валидацию не проходят адреса, в которых в имени домена содержится тире или цифры в адресе домена
my.mail@ya.ru - точка в имени пользователя (названии) является корректным символом

**Нужно исправить** Валидацию проходят следующие некорректные адреса
_@ya.ru, my---mail@site.ru - адрес не может состоять только из спецсимволов, а также содержать несколько спецсимволов подряд, начинаться и заканчиваться на спецсимволы

Номер телефона:
**Нужно исправить** Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными:
+7(925 900-90-90
+7925900-90-90
+792590090-90
+7-925-900-90-90
+7 (925) 900-90-90
+7 (925) 9009090
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
+7 925 900-90-90

Адрес сайта:
**Нужно исправить** Валидацию не проходят следующие корректные адреса сайтов:
http://ya.ru, http://x.com - доменное имя может сосотоять из одного и более символов
https://yan.academy - доменная зона может быть длинной (.travel/.academy и многие другие)
Я рекомендую вам убрать ограничение на длину доменной зоны сверху.
http://google.ru/path/to/deep/, http://google.ru/some - корректный url с путем
http://google.ru:90 - корректный url с портом
http://255.255.255.255 - корректный url с IP-адресом
http://255.255.255.255:90 - корректный url с IP-адресом + портом
**Нужно исправить** Валидацию проходят следующие  некорректные адреса
http://my-next-site.ru - rкорректное доменное имя с `-` посередине
http://some.test.yandex.ru - корректный адрес с поддоменом
gooogle.com - отсутствует протокол
http//gooogle.com - отсутствует `:`
httpssssssssssss//gooogle.com - некорректный протокол

**Comment by zlocate** [comment]
Здравствуйте. Версия, размещенная на Github Pages содержит исправления не всех проблем, отмеченных на первом ревью.
Пожалуйста проверьте что вы ее обновили и запушили изменения в репозиторий.

Актуальные проблемы:
Имя:
**Нужно исправить**: не проходят валидацию имена содержащие букву Ё.
Пример: Ерёма, Ёлка, Ёлка-Ёлка
Скрин: https://prnt.sc/rvj0b2

Email:
**Нужно исправить** Валидацию не проходят следующие корректные адреса:
some@ya-2.ru - валидацию не проходят адреса, в которых в имени домена содержится тире или цифры в адресе домена
**Нужно исправить** Валидацию проходят следующие некорректные адреса
_@ya.ru, my---mail@site.ru - адрес не может состоять только из спецсимволов, а также содержать несколько спецсимволов подряд, начинаться и заканчиваться на спецсимволы
Также валидацию проходят адреса в конце которых есть пробелы
Скрин: https://prnt.sc/rvj2sg

Номер телефона:
**Нужно исправить** следующие корректные номера телефонов не проходят валидацию
+7(925)900-90-90
+7(925) 900-90-90
+7 925-900-90-90

Адрес сайта:
**Нужно исправить** Валидацию не проходят следующие корректные адреса сайтов:
http://ya.ru, http://x.com - доменное имя может сосотоять из одного и более символов
https://yan.academy - доменная зона может быть длинной (.travel/.academy и многие другие)
Я рекомендую вам убрать ограничение на длину доменной зоны сверху.
http://google.ru/path/to/deep/, http://google.ru/some - корректный url с путем
http://google.ru:90 - корректный url с портом
http://255.255.255.255 - корректный url с IP-адресом
http://255.255.255.255:90 - корректный url с IP-адресом + портом
**Нужно исправить** Валидацию проходят следующие  некорректные адреса
http://my-next-site.ru - rкорректное доменное имя с `-` посередине
http://some.test.yandex.ru - корректный адрес с поддоменом
gooogle.com - отсутствует протокол
http//gooogle.com - отсутствует `:`
httpssssssssssss//gooogle.com - некорректный протокол

**Comment by zlocate** [comment]
Добрый вечер. Вы только что отправили работу на проверку.
На странице, размещенной на Github Pages проблемы по-прежнему присутствуют
https://prnt.sc/rvk2wz

Просьба перепроверить версию на Github Pages

**Comment by yletfull** [comment]
Доброго времени суток, все исправил.

**Comment by zlocate** [comment]
Добрый вечер.
К сожалению остались проблемы связанные с валидацией :(
Регулярные выражения:
Имя:
Валидацию проходят следующие некорректные имена: +
**Нужно исправить** Ёё------------Ёё 

Почта +
**Можно лучше** some_@ya.ru - имя ящика не может заканчиваться на спецсимвол

Адрес сайта: +
**Нужно исправить** Валидацию проходят следующие некорректные адреса: 
https:////////////////www.sss.ru - после протокола разрешено только два слеша // +

**Нужно исправить**  Валидацию не проходят следующие корректные адреса сайтов:
http://127.0.0.1 - корректный IP не проходит валидацию
http://google.ru:98/ - слеш на конце является разрешенным символом (не более 1го слешка подряд) +
https://st.some.21 - доменная зона не может состоять только из цифр +
https://*st.some.ru/ - домен не может содержать спецсимволов кроме `-` +
http://x.com:30/some - домен + порт + путь +
http://192.168.1.1:30/some - IP+порт+путь +

**Comment by zlocate** [comment]
**Можно лучше** пожалуйста синхронизируйте версии в ветках develop, master, gh-pages (во всех ветках должна быть одна версия проекта). +

**Comment by zlocate** [comment]
Добрый день. После исправления предыдущих кейсов всплыло несколько проблем.
**Нужно исправить** валидацию не проходят корректные адреса почты, в которых имя пользователя состоит из менее чем 3х символов.
ab@some.com

**Нужно исправить** доменная зона не может содержать спецсимволы http://x.s#ome
**Нужно исправить**  в доменном имени из спецсимволов разрешен только `-`

**Нужно исправить** валидацию не проходят следующие корректные адреса сайта:
http://8.8.8.8
http://127.0.0.1/
http://127.0.0.1:98/

**Нужно исправить** валидацию проходят следующие некорректные адреса сайта:
http://x.com:9999999999999999999999/some - некорректный номер порта
http://@.ru/ - некорректный домен

Следующим постом прикреплю вам список базовых кейсов для самопроверки. (к сожалению перечислить все практически невозможно, однако те, в которых чаще всего бывают ошибки присутствуют)

**Comment by zlocate** [comment]
```
Email:
Позитивные:
some2@2domains.ru - имя и домен могут содержать цифры
som-e@d-omains.ru - имя и домен могут содержать тире
some@x.com - доменное имя может состоять из одного символа
x@gmail.com - имя ящика может состоять из одного символа
t2e-s_t@g-m2ail.academy


Негативные:
_@site.ru - имя ящика не может состоять только из спецсимволов
_some_@ya.ru - имя ящика не может начинаться и заканчиваться на спецсимвол
my---mail@site.ru - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным
 - имя или домен не могут содержать запрещенные спецсимволы.
мояпочта@site.ru - имя ящика не может содержать кириллицу
-------------------@gmail.com
Hungry_developer22@яндекс.com (доменное имя или адрес не могут содержать кирилицу)
my---mail@site.ru - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным
@gmail.com - адрес электронной почты должен содержать имя пользователя (название)
test@.
test@.com
m#i#e@gmail.com 
```

По адресу сайта пожалуйста проверьте следующие наборы
IP+порт
IP+путь
IP+порт+путь
домен+порт
домен+путь
домен+порт+путь

```
Позитивные кейсы: (только не привязывайтесь к конкретным IP и доменам, я использую при проверке произвольные но соответствующие по сути)
http://ya.ru
https://www.ya.ru
http://google.ru:98/
http://x.com:30
http://google.ru/path/to/deep/
http://my-next-site.ru
http://8.8.8.8:8080
http://8.8.8.8:8080/page/to/deep#
http://some.test.yandex.ru

Негативные кейсы:
Проверку проходит следующий некорректный адреc сайта:
http://www.ya.
http://www (отсутствует доменная зона)
http://.ru (отсутствует доменное имя) 
http:something.ru (отсутствуют `//` после протокола) 
zzz://ya.ru (некорректный протокол. Допустимы только http\https)
http:\\google.ru
 httP://google.ru 
http://google.ru:/path/to/deep
https://999.999.999.999/ (у адреса ограничение: в ipv4 каждая часть адреса должна быть целым положительным числом и не больше 8 бит, те: 255)
http://something (отсутствует доменная зона)
http://1. (некорректный IP, точка на конце)
http://ya.ru:00000 (некорректный номер порта, в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными) 
http://127. (некорректный IP, точка на конце)
http://127.0..  (некорректный IP, точка на конце)
http://127.0.0.. (некорректный IP, точка на конце) 
http://127.0.0.1:8000/$ssss@# (некоректный путь - разрешены только цифры, слешы и латинские буквы, решетка (#) на конце) 
https://mysite.23 (tld не может состоять из цифр) 
http://www.google.ru/////// (в пути количество слешей подряд должно быть ограничено 1)
```
Надеюсь это облегчит вам проверку.

З.Ы Регулярки непростая для понимания, и еще более непростая на практике вещь, особенно когда речь идет о валидации строк состоящих из нескольких компонент (например адреса сайта, который может быть представлен множеством разных вариантов). 
Так что вам плюс в карму за проделанную работу однозначно :)
После того, как кейсы, описанные выше будут поправлены я буду готов засчитать работу (если не сломаются какие-либо другие критичные).

**Comment by yletfull** [comment]
Здравствуйте, не знаю зачтёте ли, но последнюю форму косо валидировал через js, потому что регулярка из regex101 в паттерне работает некорретно. К сожалению так как мой жесткий диск сгорел, в силу ограниченного времени не успел сделать по брифу(
Почту поправил. Скрин url прикрепил.
![scr](https://user-images.githubusercontent.com/63101316/79135565-37b0a780-7db8-11ea-9870-fa4c17f7a172.png)

**Comment by zlocate** [comment]
Добрый вечер. Упорство и готовность решить задачу, несмотря на возникающие трудности, пусть даже и не совсем тем способом, который требуется в задании это отлично.

Кстати, отмечу что подход используемый вами нестандартен, хоть и спорен (это вы сами понимаете), так что за это отдельный плюс. 

Но я предлагаю совместно доработать регулярное выражение.

Ваше регулярное выражение не отрабатывает при подстановке в поле pattern из-за особенностей реализации в браузере.
Студенты иногда сталкиваются с синтаксическими ошибками в регулярных выражениях, обусловленных тем, что в FF и Chrome для регулярок в поле pattern неявно применяется аттрибут /u из ES6, что накладывает ограничения на экранирование символов (**например при экранировании `@` или  `:`, `-` cыплется ошибка**)
Студенты успешно проверяют и отлаживают регулярки в веб-сервисах, копируют паттерн в страничку и ловят неочевидные ошибки (пока не введешь текст в поле и не узнаешь о том что ошибка).
Весь сок в том, что эта же самая регулярка прекрасно отработает в той же консоли браузера если дернуть от нее метод .test (т.к он по умолчанию не накладывает флаг /u)
https://www.fxsitecompat.dev/en-CA/docs/2016/input-pattern-now-sets-u-flag-for-regular-expressions/ - анонс от Mozilla
https://mathiasbynens.be/notes/es6-unicode-regex - информация о флаге `\u`

Решение проблемы - убедиться что нет избыточного экранирования указанных символов.
Попробуем доработать?

Если проблему не удастся решить самостоятельно пишите - призовем наставника на помощь.

**Comment by zlocate** [comment]
Наглядный пример каким образом можно решить данную проблему
https://stackoverflow.com/questions/41409872/invalid-escape-in-pattern-html-javascript

**Comment by zlocate** [comment]
Также отмечу что текущее выражение не слишком эффективно. 
Часть, описывающую www и доменное имя можно значительно упростить без потери функциональности

**Comment by zlocate** [comment]
@yletfull если по срокам не укладываетесь я могу в качестве исключения запросить вам 2-3 дня времени дополнительно. 
Для этого отпишитесь в данном тикете и отправьте работу на проверку через кабинет Практикума

**Comment by zlocate** [comment]
Работа принята. Мои поздравления.
Будет отлично, если вы проработаете комментарии "можно лучше"
Желаю вам успехов в учебном процессе :)
